### PR TITLE
New York Times Article Page Replica Review Request

### PR DESCRIPTION
**Pull request by SafaErden**
I and my partner finished working on the HTML and CSS "Project: Positioning and Floating Elements", kindly note that the live link demo is not functional right now on the README file because the master branch is empty. This issue will be resolved when we merge the feature branch into the master.

### CODE REVIEW

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi **TEAM**, your project is awesome 😄 it really looks exactly like the original. It has both nav and footer in a fixed position 👐 , However, we need a little fix before we can proceed. Kindly find comments below:
* The new york times logo is a link. Let us add a link to it
sup
* Let us add a ```description``` and ```email``` to our README
* For a live version without merging to master, we can use this [link](https://raw.githack.com/)
   - ```Steps```
      * Copy the index.html link in our Github ```https://github.com/SafaErden/The-New-York-Times/blob/nyt-article-page/index.html``` to the 'paste a Github placeholder input'
      * You can use the development URL for your live link
* Let us refactor our CSS file. Let us apply the DRY rule

Kindly makes these changes and submit another code review 😄 
Happy coding_ 👨‍💻 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Review by christianotieno — COMMENTED** [review]
## Pull Request under review by Christian Otieno (TSE)

**Review by christianotieno — APPROVED** [review]
# PROJECT APPROVED 🍾 
Hey @SafaErden   & @vanheaven-ui   :wave:
-

***All the required changes have been made in this project. I will go ahead and mark this as complete.*** 
- Congratulations on the splendid job team! :tada: .
##

Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

**Comment by vanheaven-ui** [comment]
Thanks. That review was helpful. 🤝

**Pull request merged**
